/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rynuk.cland.service.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CrawlerStatus implements org.apache.thrift.TEnum {
  NULL(0),
  WAITING(1),
  RUNNING(2),
  FINNISHED(3),
  READY(4);

  private final int value;

  private CrawlerStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CrawlerStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return NULL;
      case 1:
        return WAITING;
      case 2:
        return RUNNING;
      case 3:
        return FINNISHED;
      case 4:
        return READY;
      default:
        return null;
    }
  }
}
